// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tms2.Models;

namespace Tms2.Migrations
{
    [DbContext(typeof(Transportcontext))]
    [Migration("20210628061445_tmspro")]
    partial class tmspro
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Tms2.Models.Admininfo", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Username");

                    b.ToTable("admininfos");
                });

            modelBuilder.Entity("Tms2.Models.allocatevehicle", b =>
                {
                    b.Property<string>("Employeename")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Employeeage")
                        .HasColumnType("int");

                    b.Property<string>("Employeelocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Empphoneno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("vehicleallocationtoEmployee")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Employeename");

                    b.ToTable("allocatevehicles");
                });

            modelBuilder.Entity("Tms2.Models.employeeinfo", b =>
                {
                    b.Property<int>("employeeid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("age")
                        .HasColumnType("int");

                    b.Property<string>("location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phoneno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("vehicleID")
                        .HasColumnType("int");

                    b.HasKey("employeeid");

                    b.ToTable("empinfos");
                });

            modelBuilder.Entity("Tms2.Models.login", b =>
                {
                    b.Property<string>("username")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("username");

                    b.ToTable("login");
                });

            modelBuilder.Entity("Tms2.Models.modify", b =>
                {
                    b.Property<string>("employee")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("routeinfo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("vehicle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("employee");

                    b.ToTable("modifies");
                });

            modelBuilder.Entity("Tms2.Models.routeinformation", b =>
                {
                    b.Property<int>("rootnumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("stops")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("vehiclenumber")
                        .HasColumnType("int");

                    b.HasKey("rootnumber");

                    b.ToTable("routeinfos");
                });

            modelBuilder.Entity("Tms2.Models.userregistration", b =>
                {
                    b.Property<string>("User_firstname")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("User_lastname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("User_firstname");

                    b.ToTable("userregs");
                });

            modelBuilder.Entity("Tms2.Models.vehicleinformation", b =>
                {
                    b.Property<int>("vehiclenumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Availableseats")
                        .HasColumnType("int");

                    b.Property<int>("capacity")
                        .HasColumnType("int");

                    b.Property<string>("operable")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("vehiclenumber");

                    b.ToTable("vehicleinfos");
                });
#pragma warning restore 612, 618
        }
    }
}
